apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: hiremeplz
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: hiremeplz
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - port: 3000
      targetPort: http
      name: http
