apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hiremeplz-ingress
  namespace: hiremeplz
  labels:
    app.kubernetes.io/part-of: hiremeplz
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hiremeplz.info
        - api.hiremeplz.info
        - grafana.hiremeplz.info
      secretName: hiremeplz-tls
  rules:
    # Frontend: hiremeplz.info
    - host: hiremeplz.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 3000
    # Backend API: api.hiremeplz.info
    - host: api.hiremeplz.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 4000
    # Grafana dashboard: grafana.hiremeplz.info
    - host: grafana.hiremeplz.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-svc
                port:
                  number: 3000
